# Generated by Django 3.2.9 on 2022-08-29 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField(max_length=600)),
                ('image', models.ImageField(null=True, upload_to='blogs')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
